app/timetable/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectMultipleField, SelectField, BooleanField, FieldList, FormField
from wtforms.validators import InputRequired, Optional
from app.school.forms import validate_time_format, validate_date_format


class LessonForm(FlaskForm):
    start_time = StringField(validators=[InputRequired(message='Заполните это поле'), validate_time_format])
    end_time = StringField(validators=[InputRequired(message='Заполните это поле'), validate_time_format])
    subject = SelectField(choices=[], validators=[InputRequired(message='Заполните это поле')], validate_choice=False)
    school_classes = SelectMultipleField(choices=[], validators=[Optional()], validate_choice=False)
    split_classes = BooleanField()
    room = SelectField(choices=[], validators=[InputRequired(message='Заполните это поле')], validate_choice=False)
    teacher = SelectField(choices=[], validators=[InputRequired(message='Заполните это поле')], validate_choice=False)


class AddLessonsForm(FlaskForm):
    lesson_date = StringField(validators=[InputRequired(message='Заполните это поле'), validate_date_format])
    lessons = FieldList(FormField(LessonForm), min_entries=1)


class EditLessonForm(LessonForm):
    lesson_date = StringField(validators=[InputRequired(message='Заполните это поле'), validate_date_format])

app/after_school/routes.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from app import db
from .service import (
    get_after_school_students, calc_day_index, get_after_school_prices, handle_after_school_adding
)
from app.app_settings.models import SubscriptionType
from app.app_settings.service import user_action
from app.common_servicies.service import MONTHS, calc_month_index
from app.finance.service import finance_operation
from app.school.models import Person
from app.school.subjects.models import Subject, SubjectType


after_school = Blueprint('after_school', __name__)


@after_school.route('/after-school/<string:month_index>')
@login_required
def after_school_month(month_index):
    if current_user.rights in ["admin", "user", "teacher"]:
        month_index = int(month_index) if str(month_index).lstrip('-').isdigit() else 0
        after_school_subject = Subject.query.filter(Subject.subject_type.has(SubjectType.name == 'after_school')).first()
        after_school_prices = SubscriptionType.query.filter(SubscriptionType.period != '').all()
        if not after_school_prices:
            flash("Цен на продленку еще нет", 'error')
            return redirect(url_for('main.index'))

        month_students, period, current_period, date = get_after_school_students(month_index, "month")
        after_school_subject.students = month_students
        if month_index == 0:
            day_index = 0
        else:
            date = datetime(period[1], period[0], 1).date()
            day_index = calc_day_index(date)
        possible_clients = Person.query.filter(
            Person.status.in_(["Клиент", "Лид"]),
            Person.person_type == "Ребенок"
        ).order_by(Person.last_name, Person.first_name).all()
        after_school_prices = get_after_school_prices(after_school_prices)

        return render_template(
            'after_school/after_school.html', after_school_subject=after_school_subject,
            period=period, current_period=current_period, months=MONTHS, month_index=month_index,
            possible_clients=possible_clients, after_school_prices=after_school_prices, date=f'{date:%d.%m.%Y}',
            day_index=day_index, render_type="month"
        )

    else:
        flash('Нет прав администратора', 'error')
        return redirect(url_for('main.index'))


@after_school.route('/after-school-days/<string:day_index>')
@login_required
def after_school_days(day_index):
    if current_user.rights in ["admin", "user", "teacher"]:
        day_index = int(day_index) if str(day_index).lstrip('-').isdigit() else 0
        after_school_subject = Subject.query.filter(Subject.subject_type.has(SubjectType.name == 'after_school')).first()
        day_students, period, current_period, date = get_after_school_students(day_index, "day")
        after_school_subject.students = day_students
        month_index = calc_month_index(date)

        return render_template(
            'after_school/after_school.html', after_school_subject=after_school_subject,
            period=period, current_period=current_period, months=MONTHS, day_index=day_index,
            date=f'{date:%d.%m.%Y}', month_index=month_index, render_type="day"
        )

    else:
        flash('Нет прав администратора', 'error')
        return redirect(url_for('main.index'))


@after_school.route('/after-school-purchase', methods=['POST'])
@login_required
def after_school_purchase():
    try:
        if current_user.rights in ["admin", "user"]:
            attendee_id = int(request.form.get("selected_client")) if request.form.get("selected_client") else None
            if not attendee_id:
                flash('Клиент не выбран', 'error')
                return redirect(request.referrer)

            period = request.form.get("period")
            new_after_school, period_text = handle_after_school_adding(attendee_id, request.form, period)

            if not new_after_school:
                flash('Клиент уже записан на продленку', 'error')

            else:
                db.session.add(new_after_school)
                db.session.flush()
                price = new_after_school.subscription_type.price
                if new_after_school.period not in ["month", "week", "day"]:
                    hours = int(new_after_school.period.split()[0])
                    price *= hours
                operation_type = request.form.get('operation_type')
                description = f"Оплата продленки ({period_text})"
                attendee = Person.query.filter_by(id=attendee_id).first()
                finance_operation(attendee, -price, operation_type, description, "after_school", new_after_school.id)
                user_description = f"Проведение оплаты клиента {attendee.last_name} {attendee.first_name} " \
                                   f"за Продленку ({period_text})"
                user_action(current_user, user_description)
                db.session.commit()
                flash('Клиент записан на продленку', 'success')

        else:
            flash('Нет прав администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при записи на продленку: {str(e)}', 'error')

    return redirect(request.referrer)

app/timetable/routes.py
from io import BytesIO
from flask import Blueprint, request, flash, redirect, url_for, render_template, send_file
from flask_login import login_required, current_user
from wtforms.validators import InputRequired
from app import db
from app.app_settings.models import Room
from app.app_settings.service import user_action
from app.common_servicies.service import get_date, DAYS_OF_WEEK, get_today_date, calculate_week, calc_month_index
from app.school.models import Person
from app.school.subjects.models import SubjectType, Subject
from app.school.subjects.service import subjects_data
from app.school_classes.models import SchoolClass
from .forms import AddLessonsForm, EditLessonForm
from .models import Lesson
from .service import (
    student_lesson_register, week_lessons_dict, add_new_event, change_lessons_date, filter_lessons,
    copy_filtered_lessons, add_new_lessons, lesson_edit, show_lesson, handle_lesson
)
from app.common_servicies.excel_generators import download_timetable


timetable = Blueprint('timetable', __name__)


@timetable.route('/lesson-register/<string:student_id>', methods=['POST'])
@login_required
def lesson_register(student_id):
    try:
        if current_user.rights in ["admin", "user"]:
            student_id = int(student_id) if str(student_id).isdigit() else None
            student = Person.query.filter_by(id=student_id, status="Клиент").first()
            lesson, message = student_lesson_register(request.form, student)
            if lesson:
                description = f"Запись клиента {student.last_name} {student.first_name} " \
                              f"на занятие {lesson.subject.name} {lesson.date:%d.%m.%Y}"
                user_action(current_user, description)
                db.session.commit()
                flash(message, 'success')

                return redirect(url_for('timetable.lesson', lesson_str=f'1-{lesson.id}'))

            else:
                flash(message, 'error')

        else:
            flash('Нет прав администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при записи клиента: {str(e)}', 'error')

    return redirect(request.referrer)


# timetable.full_timetable
@timetable.route('/timetable/<string:week>')
@login_required
def full_timetable(week):
    week = int(week) if str(week).lstrip('-').isdigit() else 0
    week_range = [f'{get_date(day, week):%d.%m}' for day in range(7)]
    all_rooms = Room.query.all()
    week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(week, all_rooms)
    rooms = [room.name for room in all_rooms if room.name in used_rooms]
    cols = len(week_dates) * len(rooms)
    subject_types = SubjectType.query.all()
    events = Subject.query.filter(Subject.subject_type.has(SubjectType.name == 'event')).order_by(Subject.name).all()

    return render_template(
        'timetable/timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols, week=week,
        start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week_dates=week_dates,
        all_rooms=all_rooms, events=events, subject_types=subject_types, week_range=week_range
    )


@timetable.route('/extra-timetable/<string:week>')
@login_required
def extra_timetable(week):
    week = int(week) if str(week).lstrip('-').isdigit() else 0
    all_rooms = Room.query.all()
    week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(week, all_rooms, 'extra')
    rooms = [room.name for room in all_rooms if room.name in used_rooms]
    cols = len(week_dates) * len(rooms)

    return render_template(
        'timetable/extra_timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols,
        start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week=week,
        week_dates=week_dates, timetable_type='extra'
    )


@timetable.route('/individual-timetable/<string:week>')
@login_required
def individual_timetable(week):
    week = int(week) if str(week).lstrip('-').isdigit() else 0
    all_rooms = Room.query.all()
    week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(week, all_rooms, 'individual')
    rooms = [room.name for room in all_rooms if room.name in used_rooms]
    cols = len(week_dates) * len(rooms)

    return render_template(
        'timetable/extra_timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols,
        start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week=week, week_dates=week_dates,
        timetable_type='individual'
    )


@timetable.route('/teacher-timetable/<string:teacher_id>/<string:week>')
@login_required
def teacher_timetable(teacher_id, week):
    if current_user.rights in ["admin", "user", "teacher"]:
        teacher_id = int(teacher_id) if str(teacher_id).isdigit() else None
        teacher = Person.query.filter_by(id=teacher_id, teacher=True).first()
        if teacher:
            week = int(week) if str(week).lstrip('-').isdigit() else 0
            all_rooms = Room.query.all()
            week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(
                week, all_rooms, f'teacher_{teacher_id}'
            )
            rooms = [room.name for room in all_rooms if room.name in used_rooms]
            cols = len(week_dates) * len(rooms)

            return render_template(
                'timetable/teacher_timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols,
                start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week=week,
                week_dates=week_dates, lessons_teacher=teacher
            )

    else:
        flash('Нет прав администратора', 'error')
        return redirect(url_for('main.index'))


@timetable.route('/add-event', methods=['POST'])
@login_required
def add_event():
    try:
        if current_user.rights in ["admin", "user"]:
            message, event = add_new_event(request.form)
            description = f"Добавление мероприятия '{event.subject.name}' {event.date:%d.%m.%y}"
            user_action(current_user, description)
            db.session.commit()
            flash(message[0], message[1])

        else:
            flash('Нет прав администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при добавлении мероприятия: {str(e)}', 'error')

    return redirect(request.referrer)


@timetable.route('/change-lessons', methods=['POST'])
@login_required
def change_lessons():
    try:
        if current_user.rights in ["admin", "user"]:
            new_week, message, dates = change_lessons_date(request.form)
            db.session.commit()
            for msg in message:
                flash(msg[0], msg[1])
            if new_week is not None:
                description = f"Перенос занятий с {dates[0]:%d.%m.%y} на {dates[1]:%d.%m.%y}"
                user_action(current_user, description)
                db.session.commit()
                return redirect(url_for('timetable.full_timetable', week=new_week))

        else:
            flash('Нет прав администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при переносе занятий: {str(e)}', 'error')

    return redirect(request.referrer)


@timetable.route('/copy-lessons', methods=['GET', 'POST'])
@login_required
def copy_lessons():
    if current_user.rights in ["admin", "user"]:
        if request.method == 'POST':
            try:
                filtered_lessons, week_diff, next_week = filter_lessons(request.form)
                if filtered_lessons:
                    new_lessons, conflicts = copy_filtered_lessons(filtered_lessons, week_diff)
                    if new_lessons > 0:
                        week_range = (f'{get_date(0, next_week):%d.%m}-'
                                      f'{get_date(6, next_week):%d.%m.%Y}')
                        description = f'Копирование уроков в расписание на неделю {week_range}'
                        user_action(current_user, description)
                    db.session.commit()

                    if conflicts == 0:
                        flash('Все занятия добавлены в расписание.', 'success')
                    elif new_lessons == 0:
                        flash(f'Занятия не добавлены, т.к. есть занятия в это же время.', 'error')
                    else:
                        flash(f'Добавлено занятий: {new_lessons}', 'success')
                        flash(
                            f'Не добавлено занятий: {conflicts}, т.к. есть занятия в это же время', 'error'
                        )
                    return redirect(url_for('timetable.full_timetable', week=next_week))

                else:
                    flash('Нет занятий, удовлетворяющих заданным параметрам', 'error')
                    return redirect(url_for('timetable.copy_lessons'))

            except Exception as e:
                db.session.rollback()
                flash(f'Ошибка при добавлении новых занятий: {str(e)}', 'error')
                return redirect(url_for('timetable.copy_lessons'))

        subject_types = SubjectType.query.filter(SubjectType.name != 'event').all()
        rooms = Room.query.all()
        school_classes = SchoolClass.query.order_by(SchoolClass.school_class).all()
        all_teachers = Person.query.filter_by(teacher=True).order_by(Person.last_name, Person.first_name).all()
        school = SubjectType.query.filter_by(name='school').first()

        return render_template(
            'timetable/copy_lessons.html', days=DAYS_OF_WEEK, subject_types=subject_types,
            rooms=rooms, school_classes=school_classes, teachers=all_teachers, school=school
        )

    else:
        flash('Нет прав администратора', 'error')
        return redirect(url_for('timetable.full_timetable', week=0))


@timetable.route('/add-lessons', methods=['GET', 'POST'])
@login_required
def add_lessons():
    if current_user.rights in ["admin", "user"]:
        all_subjects = subjects_data()

app/templates/timetable/teacher_timetable.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card data-tables">
            <div class="card-header" data-background-color="main">
                <h4 class="title">Расписание учителя {{ lessons_teacher.last_name }} {{ lessons_teacher.first_name }}. {{ week_dates[0] }} - {{ week_dates[-1] }}</h4>
            </div>
            <div class="card-content">
                {% if classes %}
                    <div class="scroll-timetable" style="height: 80vh;">
                        <table class="table table-adjust timetable" style="min-width: {{ 10*cols + 100 }}vh;">
                            <thead class="text-success">
                                <tr>
                                    <th rowspan="2" class="fixed-column" style="border-left: 2px solid #999;">Время</th>
                                    {% for day in days[:week_dates|length] %}
                                        <th colspan="{{ rooms|length }}">{{ day }} {{ week_dates[loop.index0] }}</th>
                                    {% endfor %}
                                </tr>
                                <tr style="color: green; font-size: 80%;">
                                    {% for day in days[:week_dates|length] %}
                                        {% for room in rooms %}
                                            <th style="font-size:9px; border-bottom: 2px solid #999; border-right: 2px solid #999;">{{ room }}</th>
                                        {% endfor %}
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th class="fixed-column">{{ start_time }}:00 - {{ start_time + 1 }}:00</th>
                                    {% for day in days[:week_dates|length] %}
                                        {% for room in rooms %}
                                            <td rowspan="{{ end_time - start_time + 1 }}" style="border-bottom: 2px solid #999; {{ 'border-right: 2px solid #999;' if loop.last }}">
                                                {% if classes.get(day) %}
                                                    {% if classes[day].get(room) %}
                                                        {% for lesson in classes[day][room] %}
                                                            <div class="dropdown">
                                                                <div class="class-box dropdown-toggle" data-toggle="dropdown" id="class-box-{{ lesson.id }}"
                                                                     style="background-color: {{ lesson.color if not lesson.completed }}; top: {{ lesson.start_time - 60 * start_time + 541 }}px; height: {{ lesson.end_time - lesson.start_time - 4 }}px; {{ 'border: 1px solid #999; box-shadow: 0 0 5px rgba(0, 0, 0, 1);' if lesson.completed and lesson.lesson_type_name != 'school' else 'border: 1px solid #ffffff26;' }}">
                                                                    <p style="color: #660000;">{{ lesson.time }}</p>
                                                                    {% if lesson.lesson_type %}
                                                                        <p style="color: #003300;">{{ lesson.lesson_type }}</p>
                                                                    {% endif %}
                                                                    <p style="color: #003366;">{{ lesson.subject }}</p>
                                                                    <p style="color: #330033;">{{ lesson.teacher }}</p>
                                                                </div>
                                                                <ul class="dropdown-menu" id="dropdown-{{ lesson.id }}" style="top: {{ lesson.start_time - 60 * start_time + 560 }}px; left:10%;">
                                                                    <p style="text-align:center; font-weight:500; background-color:{{ lesson.color }}; border-radius:3px; margin: 0 5px 0 5px;">{{ lesson.subject }}</p>
                                                                    {% if lesson.lesson_type_name not in ["school", "after_school", "event"] %}
                                                                        <li>
                                                                            <a class="spinner-trigger" href="{{ url_for('timetable.lesson', lesson_str='1-'+lesson.id|string) }}">
                                                                                <i class="material-icons" style="color: purple;">info</i>Занятие
                                                                            </a>
                                                                        </li>
                                                                    {% elif lesson.lesson_type_name == "school" %}
                                                                        <li>
                                                                            <a class="spinner-trigger" href="{{ url_for('school_classes.school_lesson', lesson_str='0-'+lesson.id|string) }}">
                                                                                <i class="material-icons" style="color: purple;">book</i>Урок
                                                                            </a>
                                                                        </li>
                                                                    {% elif lesson.lesson_type_name == "after_school" %}
                                                                        <li>
                                                                            <a class="spinner-trigger" href="{{ url_for('after_school.after_school_month', month_index=lesson.month_index) }}">
                                                                                <i class="material-icons" style="color: purple;">diversity_2</i>Продленка
                                                                            </a>
                                                                        </li>
                                                                    {% endif %}
                                                                </ul>
                                                            </div>
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endif %}
                                            </td>
                                        {% endfor %}
                                    {% endfor %}
                                </tr>
                                {% for hour in range(start_time + 1, end_time) %}
                                    <tr>
                                        <th class="fixed-column" style="{{ 'border-bottom: 2px solid #999;' if loop.last }}">{{ hour }}:00 - {{ hour + 1 }}:00</th>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <p style="height: 120px; padding-top:20px;">Нет занятий в расписании</p>
                {% endif %}
                <div class="row">
                    <div class="col-md-6">
                        <button class="btn btn-sm" data-background-color="orange">
                            <a class="spinner-trigger" style="cursor:pointer; color: #FFFFFF;" href="{{ url_for('timetable.teacher_timetable', teacher_id=lessons_teacher.id, week = week - 1) }}">
                                <i class="material-icons">navigate_before</i>Предыдущая неделя
                            </a>
                        </button>
                        <button class="btn btn-sm" data-background-color="orange">
                            <a class="spinner-trigger" style="cursor:pointer; color: #FFFFFF;" href="{{ url_for('timetable.teacher_timetable', teacher_id=lessons_teacher.id, week = week + 1) }}">
                                Следующая неделя<i class="material-icons">navigate_next</i>
                            </a>
                        </button>
                    </div>
                    <div class="col-md-6">
                        {% if current_user.rights in ["admin", "user"] %}
                            <div class="dropup pull-right">
                                <button class="btn btn-sm dropdown-toggle" data-background-color="main" data-toggle="dropdown">
                                    Составить расписание
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="spinner-trigger" href="{{ url_for('timetable.copy_lessons') }}">Копировать занятия</a></li>
                                    <li><a class="spinner-trigger" href="{{ url_for('timetable.add_lessons') }}">Новые занятия</a></li>
                                </ul>
                            </div>
                        {% endif %}
                        <div class="dropup pull-right">
                            <button class="btn btn-sm dropdown-toggle" data-background-color="main" data-toggle="dropdown">
                                Расписание
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="spinner-trigger" href="{{ url_for('timetable.full_timetable', week=week) }}">Общее расписание</a></li>
                                <li><a class="spinner-trigger" href="{{ url_for('timetable.extra_timetable', week=week) }}">Расписание допов</a></li>
                                <li><a class="spinner-trigger" href="{{ url_for('timetable.individual_timetable', week=week) }}">Расписание индив</a></li>
                                <li><a class="spinner-trigger" href="{{ url_for('school_classes.school_timetable', week=week, day=0) }}">Расписание школьное</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}