app/school/employees/forms.py
from wtforms import SelectMultipleField, ColorField
from wtforms.validators import InputRequired
from app.school.forms import AdultPersonForm


class EmployeeForm(AdultPersonForm):
    roles = SelectMultipleField(choices=[], validators=[InputRequired(message='Выберете должность')],
                                validate_choice=False)
    subjects = SelectMultipleField(choices=[], validate_choice=False)
    school_classes = SelectMultipleField(choices=[], validate_choice=False)
    teacher_color = ColorField(default="#D9D9D9")

app/school/forms.py
from datetime import datetime

from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, FieldList, FormField, HiddenField, TextAreaField, BooleanField, \
    SelectMultipleField, ColorField
from wtforms.validators import InputRequired, Optional, ValidationError


def validate_date_format(form, field):
    try:
        datetime.strptime(field.data, '%d.%m.%Y')
    except ValueError:
        raise ValidationError('Неправильный формат даты')


def validate_time_format(form, field):
    try:
        datetime.strptime(field.data, '%H : %M')
    except ValueError:
        raise ValidationError('Неправильный формат')


def validate_parent_name(form, field):
    if form.contact_select.data == 'Добавить' and form.relation.data != 'Сам ребенок' and not field.data:
        raise ValidationError('Заполните это поле')


def validate_client_name(form, field):
    if form.client_select.data == 'Добавить' and not field.data:
        raise ValidationError('Заполните это поле')


class ContactForm(FlaskForm):
    telegram = StringField()
    phone = StringField()
    other_contact = StringField()


class ContForm(ContactForm):
    relation = SelectField(choices=[('Мама', 'Мама'), ('Папа', 'Папа'),
                                    ('Сам ребенок', 'Сам ребенок'), ('Другое', 'Другое контактное лицо')])
    other_relation = StringField()
    contact_select = SelectField(choices=[('Добавить', 'Добавить'), ('Выбрать', 'Выбрать из списка')])
    selected_contact = SelectField(choices=[], validate_choice=False)
    parent_last_name = StringField(validators=[validate_parent_name])
    parent_first_name = StringField(validators=[validate_parent_name])
    parent_patronym = StringField()

    def validate_selected_contact(self, field):
        if self.contact_select.data == 'Выбрать' and not field.data:
            raise ValidationError('Выберете контакт')


class ContactPersonForm(ContForm):
    primary_contact = HiddenField()


class PersonForm(FlaskForm):
    last_name = StringField(validators=[InputRequired(message='Заполните это поле')])
    first_name = StringField(validators=[InputRequired(message='Заполните это поле')])
    patronym = StringField()


class ChildForm(PersonForm):
    dob = StringField(validators=[Optional(), validate_date_format])
    status = SelectField(choices=[('Клиент', 'Клиент'), ('Лид', 'Лид')])
    contacts = FieldList(FormField(ContactPersonForm), min_entries=1)


class AdultPersonForm(ContactForm):
    client_select = SelectField(choices=[('Добавить', 'Добавить'), ('Выбрать', 'Выбрать из списка')])
    selected_client = selected_contact = SelectField(choices=[], validate_choice=False)
    last_name = StringField(validators=[validate_client_name])
    first_name = StringField(validators=[validate_client_name])
    patronym = StringField()


class AdultForm(AdultPersonForm):
    status = SelectField(choices=[('Клиент', 'Клиент'), ('Лид', 'Лид')])


class EditStudentForm(PersonForm):
    dob = StringField(validators=[Optional(), validate_date_format])
    status = SelectField(choices=[('Клиент', 'Клиент'), ('Лид', 'Лид'), ("Пауза", "Пауза"), ("Закрыт", "Закрыт")])
    pause_until = StringField(validators=[Optional(), validate_date_format])
    leaving_reason = TextAreaField()


class EditContactPersonForm(PersonForm):
    telegram = StringField()
    phone = StringField()
    other_contact = StringField()


class EditAddContPersonForm(EditContactPersonForm):
    primary_contact = BooleanField()


class AddContForm(ContactForm):
    primary_contact = BooleanField()


class NewContactPersonForm(ContForm):
    primary_contact = BooleanField()

app/school/subscriptions/forms.py
from flask_wtf import FlaskForm
from wtforms import Form, HiddenField, StringField, IntegerField, BooleanField, FieldList, FormField
from wtforms.validators import InputRequired, NumberRange
from app.school.forms import validate_date_format


class SubscriptionForm(Form):
    subscription_id = HiddenField()
    subject_name = StringField()
    lessons = IntegerField(validators=[InputRequired(message='Заполните это поле'),
                                       NumberRange(0, 20, message='Неправильный формат')])
    full_subscription = BooleanField()
    purchase_date = StringField(validators=[InputRequired(message='Заполните это поле'), validate_date_format])
    end_date = StringField(validators=[InputRequired(message='Заполните это поле'), validate_date_format])


class SubscriptionsEditForm(FlaskForm):
    subscriptions = FieldList(FormField(SubscriptionForm), min_entries=0, max_entries=20)

app/main/routes.py
from flask import render_template, Blueprint, request, flash, redirect
from flask_login import login_required, current_user
from app import db
from app.main.service import del_record


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/index')
@login_required
def index():
    return render_template('main/index.html')


@main.route('/delete-record', methods=['POST'])
@login_required
def delete_record():
    record_type = request.form.get('record_type')

    try:
        if record_type in ['student', 'employee', 'fin_operation', 'subscription']:
            if current_user.rights == 'admin':
                message = del_record(request.form, record_type, current_user)
                db.session.commit()
                flash(message[0], message[1])

            else:
                flash('Необходимо обладать правами руководителя', 'error')

        else:
            if current_user.rights in ["admin", "user"]:
                message = del_record(request.form, record_type, current_user)
                db.session.commit()
                if type(message) == list:
                    for mes in message:
                        flash(mes[0], mes[1])
                else:
                    flash(message[0], message[1])

            else:
                flash('Необходимо обладать правами администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при удалении: {str(e)}', 'error')

    return redirect(request.referrer)

app/school/__init__.py
from flask import Blueprint

school = Blueprint('school', __name__)

app/school/routes.py
from flask import request, flash
from flask_login import login_required, current_user
from app import db
from .models import Person
from flask import Blueprint


school = Blueprint('school', __name__)


@school.route('/add-comment', methods=['POST'])
@login_required
def add_comment():
    if current_user.rights in ["admin", "user"]:
        person_id = int(request.form.get('person_id'))
        comment = request.form.get('comment')
        person = Person.query.filter_by(id=person_id).first()
        person.comment = comment
        db.session.commit()

        return comment

    else:
        flash('Нет прав администратора', 'error')
        return


from .employees.routes import school_employees
school.register_blueprint(school_employees)

from .students.routes import school_students
school.register_blueprint(school_students)

from .subjects.routes import school_subjects
school.register_blueprint(school_subjects)

app/timetable/routes.py
from io import BytesIO
from flask import Blueprint, request, flash, redirect, url_for, render_template, send_file
from flask_login import login_required, current_user
from wtforms.validators import InputRequired
from app import db
from app.app_settings.models import Room
from app.app_settings.service import user_action
from app.common_servicies.service import get_date, DAYS_OF_WEEK, get_today_date, calculate_week, calc_month_index
from app.school.models import Person
from app.school.subjects.models import SubjectType, Subject
from app.school.subjects.service import subjects_data
from app.school_classes.models import SchoolClass
from .forms import AddLessonsForm, EditLessonForm
from .models import Lesson
from .service import (
    student_lesson_register, week_lessons_dict, add_new_event, change_lessons_date, filter_lessons,
    copy_filtered_lessons, add_new_lessons, lesson_edit, show_lesson, handle_lesson
)
from app.common_servicies.excel_generators import download_timetable


timetable = Blueprint('timetable', __name__)


@timetable.route('/lesson-register/<string:student_id>', methods=['POST'])
@login_required
def lesson_register(student_id):
    try:
        if current_user.rights in ["admin", "user"]:
            student_id = int(student_id) if str(student_id).isdigit() else None
            student = Person.query.filter_by(id=student_id, status="Клиент").first()
            lesson, message = student_lesson_register(request.form, student)
            if lesson:
                description = f"Запись клиента {student.last_name} {student.first_name} " \
                              f"на занятие {lesson.subject.name} {lesson.date:%d.%m.%Y}"
                user_action(current_user, description)
                db.session.commit()
                flash(message, 'success')

                return redirect(url_for('timetable.lesson', lesson_str=f'1-{lesson.id}'))

            else:
                flash(message, 'error')

        else:
            flash('Нет прав администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при записи клиента: {str(e)}', 'error')

    return redirect(request.referrer)


# timetable.full_timetable
@timetable.route('/timetable/<string:week>')
@login_required
def full_timetable(week):
    week = int(week) if str(week).lstrip('-').isdigit() else 0
    week_range = [f'{get_date(day, week):%d.%m}' for day in range(7)]
    all_rooms = Room.query.all()
    week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(week, all_rooms)
    rooms = [room.name for room in all_rooms if room.name in used_rooms]
    cols = len(week_dates) * len(rooms)
    subject_types = SubjectType.query.all()
    events = Subject.query.filter(Subject.subject_type.has(SubjectType.name == 'event')).order_by(Subject.name).all()

    return render_template(
        'timetable/timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols, week=week,
        start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week_dates=week_dates,
        all_rooms=all_rooms, events=events, subject_types=subject_types, week_range=week_range
    )


@timetable.route('/extra-timetable/<string:week>')
@login_required
def extra_timetable(week):
    week = int(week) if str(week).lstrip('-').isdigit() else 0
    all_rooms = Room.query.all()
    week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(week, all_rooms, 'extra')
    rooms = [room.name for room in all_rooms if room.name in used_rooms]
    cols = len(week_dates) * len(rooms)

    return render_template(
        'timetable/extra_timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols,
        start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week=week,
        week_dates=week_dates, timetable_type='extra'
    )


@timetable.route('/individual-timetable/<string:week>')
@login_required
def individual_timetable(week):
    week = int(week) if str(week).lstrip('-').isdigit() else 0
    all_rooms = Room.query.all()
    week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(week, all_rooms, 'individual')
    rooms = [room.name for room in all_rooms if room.name in used_rooms]
    cols = len(week_dates) * len(rooms)

    return render_template(
        'timetable/extra_timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols,
        start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week=week, week_dates=week_dates,
        timetable_type='individual'
    )


@timetable.route('/teacher-timetable/<string:teacher_id>/<string:week>')
@login_required
def teacher_timetable(teacher_id, week):
    if current_user.rights in ["admin", "user", "teacher"]:
        teacher_id = int(teacher_id) if str(teacher_id).isdigit() else None
        teacher = Person.query.filter_by(id=teacher_id, teacher=True).first()
        if teacher:
            week = int(week) if str(week).lstrip('-').isdigit() else 0
            all_rooms = Room.query.all()
            week_lessons, week_dates, used_rooms, time_range = week_lessons_dict(
                week, all_rooms, f'teacher_{teacher_id}'
            )
            rooms = [room.name for room in all_rooms if room.name in used_rooms]
            cols = len(week_dates) * len(rooms)

            return render_template(
                'timetable/teacher_timetable.html', days=DAYS_OF_WEEK, rooms=rooms, cols=cols,
                start_time=time_range[0], end_time=time_range[1], classes=week_lessons, week=week,
                week_dates=week_dates, lessons_teacher=teacher
            )

    else:
        flash('Нет прав администратора', 'error')
        return redirect(url_for('main.index'))


@timetable.route('/add-event', methods=['POST'])
@login_required
def add_event():
    try:
        if current_user.rights in ["admin", "user"]:
            message, event = add_new_event(request.form)
            description = f"Добавление мероприятия '{event.subject.name}' {event.date:%d.%m.%y}"
            user_action(current_user, description)
            db.session.commit()
            flash(message[0], message[1])

        else:
            flash('Нет прав администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при добавлении мероприятия: {str(e)}', 'error')

    return redirect(request.referrer)


@timetable.route('/change-lessons', methods=['POST'])
@login_required
def change_lessons():
    try:
        if current_user.rights in ["admin", "user"]:
            new_week, message, dates = change_lessons_date(request.form)
            db.session.commit()
            for msg in message:
                flash(msg[0], msg[1])
            if new_week is not None:
                description = f"Перенос занятий с {dates[0]:%d.%m.%y} на {dates[1]:%d.%m.%y}"
                user_action(current_user, description)
                db.session.commit()
                return redirect(url_for('timetable.full_timetable', week=new_week))

        else:
            flash('Нет прав администратора', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при переносе занятий: {str(e)}', 'error')

    return redirect(request.referrer)


@timetable.route('/copy-lessons', methods=['GET', 'POST'])
@login_required
def copy_lessons():
    if current_user.rights in ["admin", "user"]:
        if request.method == 'POST':
            try:
                filtered_lessons, week_diff, next_week = filter_lessons(request.form)
                if filtered_lessons:
                    new_lessons, conflicts = copy_filtered_lessons(filtered_lessons, week_diff)
                    if new_lessons > 0:
                        week_range = (f'{get_date(0, next_week):%d.%m}-'
                                      f'{get_date(6, next_week):%d.%m.%Y}')
                        description = f'Копирование уроков в расписание на неделю {week_range}'
                        user_action(current_user, description)
                    db.session.commit()

                    if conflicts == 0:
                        flash('Все занятия добавлены в расписание.', 'success')
                    elif new_lessons == 0:
                        flash(f'Занятия не добавлены, т.к. есть занятия в это же время.', 'error')
                    else:
                        flash(f'Добавлено занятий: {new_lessons}', 'success')
                        flash(
                            f'Не добавлено занятий: {conflicts}, т.к. есть занятия в это же время', 'error'
                        )
                    return redirect(url_for('timetable.full_timetable', week=next_week))

                else:
                    flash('Нет занятий, удовлетворяющих заданным параметрам', 'error')
                    return redirect(url_for('timetable.copy_lessons'))

            except Exception as e:
                db.session.rollback()
                flash(f'Ошибка при добавлении новых занятий: {str(e)}', 'error')
                return redirect(url_for('timetable.copy_lessons'))

        subject_types = SubjectType.query.filter(SubjectType.name != 'event').all()
        rooms = Room.query.all()
        school_classes = SchoolClass.query.order_by(SchoolClass.school_class).all()
        all_teachers = Person.query.filter_by(teacher=True).order_by(Person.last_name, Person.first_name).all()
        school = SubjectType.query.filter_by(name='school').first()

        return render_template(
            'timetable/copy_lessons.html', days=DAYS_OF_WEEK, subject_types=subject_types,
            rooms=rooms, school_classes=school_classes, teachers=all_teachers, school=school
        )

    else:
        flash('Нет прав администратора', 'error')
        return redirect(url_for('timetable.full_timetable', week=0))


@timetable.route('/add-lessons', methods=['GET', 'POST'])
@login_required
def add_lessons():
    if current_user.rights in ["admin", "user"]:
        all_subjects = subjects_data()

app/templates/school_classes/school_timetable.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card data-tables">
            <div class="card-header" data-background-color="main">
                <h4 class="title">Школьное расписание</h4>
            </div>
            <div class="card-content" style="padding: 10px 20px;">
                <div class="row" style="margin-left:30px;">
                    {% for day in days[:5] %}
                        <button type="button"
                                class="btn btn-sm {{ 'btn-success' if loop.index==week_day else '' }}"
                                style="width:130px; padding: 5px 5px; margin-top: 1px;">
                            <a class="spinner-trigger" style="cursor:pointer; color: #FFFFFF;" href="{{ url_for('school_classes.school_timetable', week=week, day=loop.index) }}">
                                {{ day }}, {{ dates[loop.index0] }}
                            </a>
                        </button>
                    {% endfor %}
                    <div class="dropdown" style="display:inline;">
                        <button class="btn btn-sm dropdown-toggle {{ 'btn-success' if week_day in [6, 7] else '' }}" data-toggle="dropdown" style="width:130px; padding: 5px 5px; margin-top: 1px;">
                            Выходные
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="spinner-trigger" href="{{ url_for('school_classes.school_timetable', week=week, day=6) }}">
                                    {{ days[5] }}, {{ dates[5] }}
                                </a>
                            </li>
                            <li>
                                <a class="spinner-trigger" href="{{ url_for('school_classes.school_timetable', week=week, day=7) }}">
                                    {{ days[6] }}, {{ dates[6] }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                {% if classes %}
                    <div class="scroll-timetable" style="height: 72vh;">
                        <table class="table table-adjust school-timetable">
                            <thead class="text-success">
                                <tr>
                                    <th width="8%" style="border-left: 2px solid #999;">Время</th>
                                    {% for school_class in school_classes %}
                                        {% if classes.get(school_class.school_name) %}
                                            <th>{{ school_class.school_name }}</th>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>{{ start_time }}:00 - {{ start_time + 1 }}:00</th>
                                    {% for school_class in school_classes %}
                                        {% if classes.get(school_class.school_name) %}
                                            <td rowspan="{{ end_time - start_time + 1 }}" style="border-bottom: 2px solid #999; {{ 'border-right: 2px solid #999;' if loop.last }}">
                                                {% for lesson in classes[school_class.school_name] %}
                                                    <div class="dropdown">
                                                        <div class="class-box dropdown-toggle" data-toggle="dropdown" id="class-box-{{ lesson.id }}"
                                                             style="background-color: {{ lesson.room_color if not lesson.completed }}; top: {{ lesson.start_time - 60 * start_time + 541 }}px; height: {{ lesson.end_time - lesson.start_time - 1 }}px; {{ 'border: 1px solid #777; box-shadow: 0 0 5px rgba(0, 0, 0, 1);' if lesson.completed else 'border: 1px solid #ffffff26;' }}"
                                                             title="{{ lesson.room }}">
                                                            <p style="color: #660000;">{{ lesson.time }}</p>
                                                            <p style="color: #003366;">{{ lesson.subject }}</p>
                                                            <p style="color: #330033;">{{ lesson.teacher }}</p>
                                                            <input type="hidden" value="{{ lesson.split }}">
                                                        </div>
                                                        <ul class="dropdown-menu" id="dropdown-{{ lesson.id }}" style="top: {{ lesson.start_time - 60 * start_time + 560 }}px; left:10%;">
                                                            <li><a class="spinner-trigger" href="{{ url_for('school_classes.school_lesson', lesson_str='0-'+lesson.id|string) }}">Урок</a></li>
                                                            {% if not lesson.completed and lesson.month_index >= -1 and current_user.rights in ["admin", "user"]  %}
                                                                <li><a class="spinner-trigger" href="{{ url_for('timetable.edit_lesson', lesson_id=lesson.id) }}">Изменить</a></li>
                                                                <li class="divider"></li>
                                                                <li>
                                                                    <a href="#" data-toggle="modal" data-target="#delete-{{ lesson.id }}-modal">
                                                                        <i class="material-icons" style="color: red;">delete_forever</i>Отменить
                                                                    </a>
                                                                </li>
                                                            {% endif %}
                                                        </ul>
                                                    </div>

                                            <!-- *-*-*-*-*-*-*-*-*-* Lesson delete conformation *-*-*-*-*-*-*-*-*-* -->

                                                    <div class="modal fade" id="delete-{{ lesson.id }}-modal" role="dialog">
                                                        <div class="modal-dialog modal-sm">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h4 class="modal-title alert alert-danger" style="text-align:center;">Отмена занятия</h4>
                                                                </div>
                                                                <div class="modal-body" style="padding-top:10px;">
                                                                    <p class="control-label">
                                                                        Вы уверены, что хотите отменить урок {{ lesson.subject_full }}?
                                                                    </p>
                                                                    <form class="login-form" action="{{ url_for('main.delete_record') }}" method="post">
                                                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                                                        <input type="hidden" name="record_type" value="lesson">
                                                                        <input type="hidden" name="lesson_id" value="{{ lesson.id }}">
                                                                        <div class="row">
                                                                            <div class="col-md-10 col-md-offset-1">
                                                                                <button type="submit" class="btn btn-sm" data-background-color="main">
                                                                                    Да
                                                                                </button>
                                                                                <button type="button" class="btn btn-sm pull-right" data-dismiss="modal" data-background-color="red">
                                                                                    Нет
                                                                                </button>
                                                                            </div>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                {% endfor %}
                                            </td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                                {% for hour in range(start_time + 1, end_time) %}
                                    <tr>
                                        <th style="{{ 'border-bottom: 2px solid #999;' if loop.last }}">{{ hour }}:00 - {{ hour + 1 }}:00</th>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <p style="height: 120px; padding-top:20px;">Нет уроков в расписании</p>
                {% endif %}
                <div class="row">
                    <div class="col-md-6">
                        <button class="btn btn-sm" style="background-color: #ff9800;">
                            <a class="spinner-trigger" style="cursor:pointer; color: #FFFFFF;" href="{{ url_for('school_classes.school_timetable', week=week-1, day=1) }}">
                                <i class="material-icons">navigate_before</i>Предыдущая неделя
                            </a>
                        </button>
                        <button class="btn btn-sm" style="background-color: #ff9800;">
                            <a class="spinner-trigger" style="cursor:pointer; color: #FFFFFF;" href="{{ url_for('school_classes.school_timetable', week=week+1, day=1) }}">
                                Следующая неделя<i class="material-icons">navigate_next</i>
                            </a>
                        </button>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-sm pull-right" data-background-color="main">
                            <a style="cursor:pointer; color: #FFFFFF;" href="{{ url_for('timetable.generate_timetable', week=week) }}" download=" {{ filename }} ">
                                <i class="material-icons">file_download</i> Скачать
                            </a>
                        </button>
                        {% if current_user.rights in ["admin", "user"] %}
                            <div class="dropup pull-right">
                                <button class="btn btn-sm dropdown-toggle" data-background-color="main" data-toggle="dropdown">
                                    Составить расписание
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="spinner-trigger" href="{{ url_for('timetable.copy_lessons') }}">Копировать занятия</a></li>
                                    <li><a class="spinner-trigger" href="{{ url_for('timetable.add_lessons') }}">Новые занятия</a></li>
                                </ul>
                            </div>
                        {% endif %}
                        <div class="dropup pull-right">
                            <button class="btn btn-sm dropdown-toggle" data-background-color="main" data-toggle="dropdown">
                                Расписание
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="spinner-trigger" href="{{ url_for('timetable.full_timetable', week=week) }}">Общее расписание</a></li>
                                <li><a class="spinner-trigger" href="{{ url_for('timetable.extra_timetable', week=week) }}">Расписание допов</a></li>
                                <li><a class="spinner-trigger" href="{{ url_for('timetable.individual_timetable', week=week) }}">Расписание индив</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}