app/app_settings/models.py
from app import db
from datetime import datetime
from app.common_servicies.service import LOCAL_TZ


class Room(db.Model):
    __tablename__ = 'rooms'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    color = db.Column(db.String(16))

    def __repr__(self):
        return f"<Room {self.id}: {self.name}>"


class SubscriptionType(db.Model):
    __tablename__ = 'subscription_types'

    id = db.Column(db.Integer, primary_key=True)
    lessons = db.Column(db.Integer)
    period = db.Column(db.String(50), default="")
    duration = db.Column(db.Integer)
    price = db.Column(db.Numeric(8, 2))
    subscriptions = db.relationship('Subscription', backref='subscription_type')

    def __repr__(self):
        if self.lessons:
            return f"<SubscriptionType {self.id}: lessons {self.lessons}, price {self.price}>"

        elif self.duration:
            return f"<SubscriptionType {self.id}: duration {self.duration}, price {self.price}>"

        else:
            return f"<SubscriptionType {self.id}: price {self.price}>"


class UserAction(db.Model):
    __tablename__ = 'user_actions'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    user = db.relationship('User', backref='actions')
    timestamp = db.Column(db.DateTime, default=lambda: datetime.now(LOCAL_TZ))
    description = db.Column(db.String(120))


class SchoolSemester(db.Model):
    __tablename__ = 'school_semesters'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)
    school_year = db.Column(db.String(20))

app/app_settings/routes.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from app.app_settings.models import Room, SubscriptionType, SchoolSemester
from app.app_settings.service import user_action, calculate_school_year, validate_semester
from app import db
from app.auth.models import User
from app.school.models import Person
from app.school_classes.models import SchoolClass
from app.caching.service import get_cache_rooms, get_cache_subscription_types, get_cache_school_attending_students, \
    get_cache_after_school_prices, get_cache_parent_users, get_cache_school_classes, delete_cache, get_cache_semesters

app_settings = Blueprint('settings', __name__)


@app_settings.route('/settings')
@login_required
def settings():
    if current_user.rights in ['admin', 'user']:

        rooms = get_cache_rooms()
        school_classes = get_cache_school_classes()
        subscription_types = get_cache_subscription_types()
        after_school_prices = get_cache_after_school_prices()
        school_children = get_cache_school_attending_students()
        parent_users = get_cache_parent_users()
        semesters = get_cache_semesters()
        semester_names = ["1 четверть", "2 четверть", "3 четверть", "4 четверть"]

        return render_template('app_settings/settings.html', rooms=rooms, parents=parent_users,
                               children=school_children, school_classes=school_classes,
                               subscription_types=subscription_types, after_school_prices=after_school_prices,
                               semesters=semesters, semester_names=semester_names
                               )

    else:
        return render_template('app_settings/settings.html')


@app_settings.route('/change_parent', methods=['POST'])
@login_required
def change_parent():
    try:
        if current_user.rights == 'admin':
            if 'change_parent_btn' in request.form:
                parent_id = int(request.form.get('change_parent_btn'))
                children_ids = request.form.getlist(f'children_{parent_id}')
                parent = User.query.filter_by(id=parent_id).first()

                if parent and children_ids:
                    children_ids = [int(child_id) for child_id in children_ids]
                    children = Person.query.filter(
                        Person.id.in_(children_ids),
                        Person.school_class_id.is_not(None)
                    ).all()
                    if set(parent.user_persons) != set(children):
                        parent.user_persons = [child for child in children]
                        user_action(current_user, f"Изменение списка детей у родителя {parent.username}")
                        db.session.commit()
                        delete_cache(['parent_users'])
                        flash("Изменения внесены", 'success')

                elif parent and not children_ids:
                    flash("Не выбраны дети", 'error')

                else:
                    flash("Такого родителя нет", 'error')

            if 'delete_parent_btn' in request.form:
                parent_id = int(request.form.get('delete_parent_btn'))
                parent = User.query.filter_by(id=parent_id).first()
                db.session.delete(parent)
                user_action(current_user, f"Удаление родителя {parent.username}")
                db.session.commit()
                delete_cache(['parent_users'])
                flash(f"Родитель {parent.username} удален", 'success')

        else:
            flash('Нет прав руководителя', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при изменении родителя: {str(e)}', 'error')

    return redirect(url_for('settings.settings'))


@app_settings.route('/change-add-room', methods=['POST'])
@login_required
def change_add_room():
    try:
        if current_user.rights == 'admin':
            if 'change_room_btn' in request.form:
                room_id = int(request.form.get('change_room_btn')) if request.form.get('change_room_btn').isdigit() \
                    else None
                new_name = request.form.get(f'name_{room_id}')
                new_color = request.form.get(f'color_{room_id}')
                room = Room.query.filter_by(id=room_id).first()
                if room and new_name and new_color:
                    room.name = new_name
                    room.color = new_color
                    user_action(current_user, f"Внесение изменений в кабинет '{room.name}'")
                    db.session.commit()
                    delete_cache(['rooms'])
                    flash(f"Кабинет '{room.name}' изменен", 'success')

            if 'delete_room_btn' in request.form:
                room_id = int(request.form.get('delete_room_btn')) if request.form.get('delete_room_btn').isdigit() \
                    else None
                room = Room.query.filter_by(id=room_id).first()
                if room:
                    db.session.delete(room)
                    user_action(current_user, f"Удаление кабинета '{room.name}'")
                    db.session.commit()
                    delete_cache(['rooms'])
                    flash(f"Кабинет '{room.name}' удален", 'success')

            if 'add_room' in request.form:
                room_name = request.form.get('room_name')
                room_color = request.form.get('room_color')
                new_room = Room(name=room_name, color=room_color)
                db.session.add(new_room)
                user_action(current_user, f"Добавление кабинета '{new_room.name}'")
                db.session.commit()
                delete_cache(['rooms'])
                flash(f"Новый кабинет '{new_room.name}' добавлен в систему", 'success')

        else:
            flash('Нет прав руководителя', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при добавлении/изменении кабинета: {str(e)}', 'error')

    return redirect(url_for('settings.settings'))


@app_settings.route('/change-add-class', methods=['POST'])
@login_required
def change_add_class():
    try:
        if current_user.rights == 'admin':
            if 'change_class_btn' in request.form:
                class_id = int(request.form.get('change_class_btn')) if request.form.get('change_class_btn').isdigit() \
                    else None
                new_school_class = int(request.form.get(f'class_{class_id}')) \
                    if request.form.get(f'class_{class_id}').isdigit() else None
                new_school_name = request.form.get(f'name_{class_id}')
                school_class = SchoolClass.query.filter_by(id=class_id).first()
                if school_class and new_school_class and new_school_name:
                    school_class.school_class = new_school_class
                    school_class.school_name = new_school_name
                    user_action(current_user, f"Внесение изменений в класс '{school_class.school_name}'")
                    db.session.commit()
                    delete_cache(['classes_school', f'class_info_{school_class.id}'])
                    flash(f"Класс '{school_class.school_name}' изменен", 'success')

            if 'delete_class_btn' in request.form:
                class_id = int(request.form.get('delete_class_btn')) if request.form.get('delete_class_btn').isdigit() \
                    else None
                school_class = SchoolClass.query.filter_by(id=class_id).first()
                if school_class:
                    db.session.delete(school_class)
                    user_action(current_user, f"Удаление класса '{school_class.school_name}'")
                    db.session.commit()
                    delete_cache(['classes_school', f'class_info_{school_class.id}'])
                    flash(f"Класс '{school_class.school_name}' удален", 'success')

            if 'add_class' in request.form:
                new_school_class = int(request.form.get('new_school_class')) \
                    if request.form.get('new_school_class').isdigit() else None
                new_school_name = request.form.get('new_school_name')
                new_class = SchoolClass(school_class=new_school_class, school_name=new_school_name)
                db.session.add(new_class)
                user_action(current_user, f"Добавление класса '{new_class.school_name}'")
                db.session.commit()
                delete_cache(['classes_school'])
                flash(f"Новый класс '{new_class.school_name}' добавлен в систему", 'success')

        else:
            flash('Нет прав руководителя', 'error')

    except Exception as e:
        db.session.rollback()
        flash(f'Ошибка при добавлении/изменении кабинета: {str(e)}', 'error')

    return redirect(url_for('settings.settings'))


@app_settings.route('/change-add-subscription', methods=['POST'])
@login_required
def change_add_subscription():
    try:
        if current_user.rights == 'admin':
            if 'change_subscription_btn' in request.form:
                subscription_type_id = int(request.form.get('change_class_subscription')) \
                    if request.form.get('change_class_subscription').isdigit() else None
                subscription_lessons = int(request.form.get(f'lessons_{subscription_type_id}')) \
                    if request.form.get(f'lessons_{subscription_type_id}').isdigit() else None
                subscription_duration = int(request.form.get(f'duration_{subscription_type_id}')) \
                    if request.form.get(f'duration_{subscription_type_id}').isdigit() else None
                subscription_price = request.form.get(f'price_{subscription_type_id}').replace(',', '.')
                if not subscription_price.replace('.', '').isdigit():
                    flash('Неправильный формат цены', 'error')
                    return redirect(url_for('settings.settings'))

app/templates/app_settings/add_parent.html
<div class="row" style="margin-left:30px;">
    <button class="btn btn-sm" data-background-color="orange" style="width:200px;">
        <a href="#" data-toggle="collapse" data-target="#add-parent">
            <i class="material-icons">group_add</i> Родители
        </a>
    </button>
</div>
<div  class="collapse" id="add-parent">
    <form class="change-class-form" method="post" action="{{ url_for('settings.change_parent') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-md-4">Имя пользователя:</label>
                    <label class="control-label col-md-4">Дети:</label>
                </div>
                {% for parent in parents %}
                    <div class="row parent-row" data-target="{{ parent.id }}">
                        <div class="col-md-4" style="padding-left:44px;">
                            <div class="form-control">{{ parent.username }}</div>
                        </div>
                        <div class="col-md-4" style="padding-left:44px;">
                            <div class="form-control">
                                <div class="children-container">
                                    {% for child in parent.children %}
                                        <p class="child-p">
                                            <button type="button" value="{{ child.id }}" class="btn btn-danger del-btn del-child-btn" style="margin-bottom:2px">&times;</button>
                                            <span class="child-name">{{ child.last_name }} {{ child.first_name }}</span>
                                            <input type="hidden" name="children_{{ parent.id }}" value="{{ child.id }}">
                                        </p>
                                    {% endfor %}
                                </div>
                                <select class="form-control select-search child-select" placeholder="Добавить ребенка">
                                    <option value="" selected disabled></option>
                                    {% for child in children %}
                                        {% if child not in parent.user_persons %}
                                            <option value="{{ child.id }}">{{ child.last_name }} {{ child.first_name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>

                            </div>
                        </div>
                        <div class="col-md-3">
                            <button type="submit" name="change_parent_btn" value="{{ parent.id }}" class="btn btn-xs" style="margin:0;" data-background-color="main"><i class="material-icons">done</i></button>
                            <button type="submit" name="delete_parent_btn" value="{{ parent.id }}" class="btn btn-xs" style="margin:0;" data-background-color="red"><i class="material-icons">delete</i></button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </form>
    <form class="add-parent-form" method="post" action="{{ url_for('settings.create_user') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <h4 class="title" style="margin-left: 27px;">Добавить родителя</h4>
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-md-3">Имя пользователя:</label>
                    <div class="col-md-4 field-div">
                        <input type="text" name="username" class="form-control field-input required">
                    </div>
                </div>
                <div class="row">
                    <label class="control-label col-md-3">Пароль:</label>
                    <div class="col-md-4 password-div">
                        <input name="password" type="password" class="form-control password-input">
                    </div>
                    <div class="col-md-1">
                        <span class="material-icons" style="cursor:pointer; margin:5px 0 0 -55px; color:#AAAAAA;" title="Не менее 7 символов, латинские буквы и цифры, символы не обязательно">help_outline</span>
                    </div>
                </div>
                <div class="row">
                    <label class="control-label col-md-3">Повторить пароль:</label>
                    <div class="col-md-4 repeat-password-div">
                        <input type="password" name="repeat_password" class="form-control repeat-password-input">
                    </div>
                </div>
                <input type="hidden" name="rights" value="parent">
                <div class="row">
                    <label class="control-label col-md-3">Дети:</label>
                    <div class="col-md-4">
                        <select name="children" class="form-control select-search" multiple>
                            {% for child in children %}
                                <option value="{{ child.id }}">{{ child.last_name }} {{ child.first_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="row" style="margin-left:30px;">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-sm" data-background-color="main">Добавить</button>
                    <button type="button" class="btn btn-sm" data-background-color="red" data-toggle="collapse" data-target="#add-parent">Закрыть</button>
                </div>
            </div>
        </div>
    </form>
</div>

app/templates/app_settings/change_add_classes.html
<div class="row" style="margin-left:30px;">
    <button class="btn btn-sm" data-background-color="orange" style="width:200px;">
        <a href="#" data-toggle="collapse" data-target="#school_classes">
            <i class="material-icons">school</i> Классы
        </a>
    </button>
</div>
<div  class="collapse" id="school_classes">
    <form class="change-class-form" method="post" action="{{ url_for('settings.change_add_class') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <div class="form-group">
                {% for school_class in school_classes %}
                    <div class="row">
                        <label class="control-label col-md-2">Класс:</label>
                        <div class="col-md-2 field-div">
                            <input type="number" name="class_{{ school_class.id }}" min="1" max="11" value="{{ school_class.school_class }}" class="form-control field-input required">
                        </div>
                        <label class="control-label col-md-2">Название:</label>
                        <div class="col-md-2 field-div">
                            <input type="text" name="name_{{ school_class.id }}" value="{{ school_class.school_name }}" class="form-control field-input required">
                        </div>
                        <div class="col-md-3">
                            <button type="submit" name="change_class_btn" value="{{ school_class.id }}" class="btn btn-xs" style="margin:0;" data-background-color="main"><i class="material-icons">done</i></button>
                            {% if not school_class.class_lessons %}
                                <button type="submit" name="delete_class_btn" value="{{ school_class.id }}" class="btn btn-xs" style="margin:0;" data-background-color="red"><i class="material-icons">delete</i></button>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </form>
    <form class="add-class-form" method="post" action="{{ url_for('settings.change_add_class') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <h4 class="title" style="margin-left: 27px;">Добавить класс</h4>
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-md-2">Класс:</label>
                    <div class="col-md-2 field-div">
                        <input type="number" name="new_school_class" min="1" max="11" class="form-control field-input required">
                    </div>
                    <label class="control-label col-md-2">Название:</label>
                    <div class="col-md-3 field-div">
                        <input type="text" name="new_school_name" class="form-control field-input required">
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="row" style="margin-left:30px;">
                <div class="col-md-6">
                    <button type="submit" name="add_class" class="btn btn-sm" data-background-color="main">Добавить</button>
                    <button type="button" class="btn btn-sm" data-background-color="red" data-toggle="collapse" data-target="#school_classes">Закрыть</button>
                </div>
            </div>
        </div>
    </form>
</div>

app/templates/app_settings/change_add_room.html
<div class="row" style="margin-left:30px;">
    <button class="btn btn-sm" data-background-color="orange" style="width:200px;">
        <a href="#" data-toggle="collapse" data-target="#rooms">
            <i class="material-icons">meeting_room</i> Кабинеты
        </a>
    </button>
</div>
<div  class="collapse" id="rooms">
    <form class="change-room-form" method="post" action="{{ url_for('settings.change_add_room') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <div class="form-group">
                {% for room in rooms %}
                    <div class="row">
                        <label class="control-label col-md-2">Название:</label>
                        <div class="col-md-3 field-div">
                            <input type="text" name="name_{{ room.id }}" value="{{ room.name }}" class="form-control field-input required">
                        </div>
                        <label class="control-label col-md-2">Цвет:</label>
                        <div class="col-md-1">
                            <input type="color" name="color_{{ room.id }}" value="{{ room.color }}">
                        </div>
                        <div class="col-md-3">
                            <button type="submit" name="change_room_btn" value="{{ room.id }}" class="btn btn-xs" style="margin:0;" data-background-color="main"><i class="material-icons">done</i></button>
                            {% if not room.lessons %}
                                <button type="submit" name="delete_room_btn" value="{{ room.id }}" class="btn btn-xs" style="margin:0;" data-background-color="red"><i class="material-icons">delete</i></button>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </form>
    <form class="add-room-form" method="post" action="{{ url_for('settings.change_add_room') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <h4 class="title" style="margin-left: 27px;">Добавить кабинет</h4>
            <div class="form-group">
                <div class="row">
                    <label class="control-label col-md-2">Название:</label>
                    <div class="col-md-3 field-div">
                        <input type="text" name="room_name" class="form-control field-input required">
                    </div>
                    <label class="control-label col-md-2">Цвет:</label>
                    <div class="col-md-1">
                        <input type="color" name="room_color" value="#D9D9D9">
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="row" style="margin-left:30px;">
                <div class="col-md-6">
                    <button type="submit" name="add_room" class="btn btn-sm" data-background-color="main">Добавить</button>
                    <button type="button" class="btn btn-sm" data-background-color="red" data-toggle="collapse" data-target="#rooms">Закрыть</button>
                </div>
            </div>
        </div>
    </form>
</div>

app/templates/app_settings/change_add_subscription.html
<div class="row" style="margin-left:30px;">
    <button class="btn btn-sm" data-background-color="orange" style="width:200px;">
        <a href="#" data-toggle="collapse" data-target="#subscriptions">
            <i class="material-icons">ballot</i> Абонементы
        </a>
    </button>
</div>
<div  class="collapse" id="subscriptions">
    <form class="change-subscription-form" method="post" action="{{ url_for('settings.change_add_subscription') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-8 table-responsive" style="padding-left:44px;">
                        <table class="table table-hover" style="table-layout: fixed;">
                            <thead class="text-success">
                                <th>Занятия</th>
                                <th>Срок действия</th>
                                <th>Цена</th>
                                <th></th>
                            </thead>
                            <tbody>
                                {% for subscription_type in subscription_types %}
                                    <tr>
                                        <td style="vertical-align:top;" class="field-div">
                                            <input type="number" name="lessons_{{ subscription_type.id }}" min="1" value="{{ subscription_type.lessons }}" class="form-control field-input required">
                                        </td>
                                        <td style="vertical-align:top;" class="field-div">
                                            <input type="number" name="duration_{{ subscription_type.id }}" min="1" value="{{ subscription_type.duration }}" class="form-control field-input required">
                                        </td>
                                        <td style="vertical-align:top;" class="field-div">
                                            <input type="number" name="price_{{ subscription_type.id }}" min="1" value="{{ subscription_type.price }}" class="form-control float-field field-input required">
                                        </td>
                                        <td style="vertical-align:top;">
                                            <button type="submit" name="change_subscription_btn" value="{{ subscription_type.id }}" class="btn btn-xs" style="margin:5px 0;" data-background-color="main"><i class="material-icons">done</i></button>
                                            {% if not subscription_type.subscriptions %}
                                                <button type="submit" name="delete_subscription_btn" value="{{ subscription_type.id }}" class="btn btn-xs" style="margin:5px 0;" data-background-color="red"><i class="material-icons">delete</i></button>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <form class="add-subscription-form" method="post" action="{{ url_for('settings.change_add_subscription') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="row">
            <h4 class="title" style="margin-left: 27px;">Добавить абонемент</h4>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                            <label class="control-label">Занятия:</label>
                        </div>
                        <div class="row field-div" style="padding: 0 20px 0 44px; margin-top:0;">
                            <input type="number" name="new_subscription_lessons" min="1" value="8" class="form-control field-input required">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="row">
                            <label class="control-label">Срок действия:</label>
                        </div>
                        <div class="row field-div" style="padding: 0 20px 0 44px; margin-top:0;">
                            <input type="number" name="new_subscription_duration" min="1" value="40" class="form-control field-input required">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="row">
                            <label class="control-label">Цена:</label>
                        </div>
                        <div class="row field-div" style="padding: 0 20px 0 44px; margin-top:0;">
                            <input type="number" name="new_subscription_price" min="1" value="90.0" class="form-control float-field field-input required">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer" style="margin-top:-30px;">
            <div class="row" style="margin-left:30px;">
                <div class="col-md-6">
                    <button type="submit" name="add_subscription" class="btn btn-sm" data-background-color="main">Добавить</button>
                    <button type="button" class="btn btn-sm" data-background-color="red" data-toggle="collapse" data-target="#subscriptions">Закрыть</button>
                </div>
            </div>
        </div>
    </form>
</div>